modLoader="javafml"
loaderVersion="[41,)"
license="All Rights Reserved"
showAsResourcePack=false

[[mods]]
modId="customToolTipsForEnchantedGear"
version="0.1"
displayName="Custom tool tips for enchanted gear"
credits="Nicer 1.19.2 ohne freshe tool tips."
authors="Alexander Pissinger"
description='Customize the look of tool tips for mostly enchanted weapons, tools and armor'

[[dependencies.customToolTipsForEnchantedGear]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.customToolTipsForEnchantedGear]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.2)"
ordering="NONE"
side="BOTH"